name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      shell: cmd
      run: docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%

    - name: Build and Push Docker Image
      shell: cmd
      run: |
        docker build -t %DOCKER_USERNAME%/demo-app:latest .
        docker push %DOCKER_USERNAME%/demo-app:latest

    - name: Deploy to Kubernetes
      shell: cmd
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
