name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
    # Step 1: Checkout code from GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest
      shell: cmd

    # Step 4: Set up kubectl (already installed on Windows runner)
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.0'

    # Step 5: Deploy to Kubernetes (Minikube)
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
      shell: cmd
