name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Windows self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      shell: pwsh
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build and Push Docker Image
      shell: pwsh
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest

    - name: Deploy to Kubernetes
      shell: pwsh
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
